-- Seeder for master_sizes table with common shoe sizes

-- Insert EU sizes
INSERT INTO master_sizes (value, unit, tanggal_update) VALUES
('35', 'EU', CURRENT_TIMESTAMP),
('36', 'EU', CURRENT_TIMESTAMP),
('37', 'EU', CURRENT_TIMESTAMP),
('38', 'EU', CURRENT_TIMESTAMP),
('39', 'EU', CURRENT_TIMESTAMP),
('40', 'EU', CURRENT_TIMESTAMP),
('41', 'EU', CURRENT_TIMESTAMP),
('42', 'EU', CURRENT_TIMESTAMP),
('43', 'EU', CURRENT_TIMESTAMP),
('44', 'EU', CURRENT_TIMESTAMP),
('45', 'EU', CURRENT_TIMESTAMP),
('46', 'EU', CURRENT_TIMESTAMP),
('47', 'EU', CURRENT_TIMESTAMP),
('48', 'EU', CURRENT_TIMESTAMP)
ON CONFLICT (value, unit) DO UPDATE
SET tanggal_update = CURRENT_TIMESTAMP;

-- Insert US Men's sizes
INSERT INTO master_sizes (value, unit, tanggal_update) VALUES
('5', 'US Men', CURRENT_TIMESTAMP),
('5.5', 'US Men', CURRENT_TIMESTAMP),
('6', 'US Men', CURRENT_TIMESTAMP),
('6.5', 'US Men', CURRENT_TIMESTAMP),
('7', 'US Men', CURRENT_TIMESTAMP),
('7.5', 'US Men', CURRENT_TIMESTAMP),
('8', 'US Men', CURRENT_TIMESTAMP),
('8.5', 'US Men', CURRENT_TIMESTAMP),
('9', 'US Men', CURRENT_TIMESTAMP),
('9.5', 'US Men', CURRENT_TIMESTAMP),
('10', 'US Men', CURRENT_TIMESTAMP),
('10.5', 'US Men', CURRENT_TIMESTAMP),
('11', 'US Men', CURRENT_TIMESTAMP),
('11.5', 'US Men', CURRENT_TIMESTAMP),
('12', 'US Men', CURRENT_TIMESTAMP),
('12.5', 'US Men', CURRENT_TIMESTAMP),
('13', 'US Men', CURRENT_TIMESTAMP),
('13.5', 'US Men', CURRENT_TIMESTAMP),
('14', 'US Men', CURRENT_TIMESTAMP)
ON CONFLICT (value, unit) DO UPDATE
SET tanggal_update = CURRENT_TIMESTAMP;

-- Insert US Women's sizes
INSERT INTO master_sizes (value, unit, tanggal_update) VALUES
('5', 'US Women', CURRENT_TIMESTAMP),
('5.5', 'US Women', CURRENT_TIMESTAMP),
('6', 'US Women', CURRENT_TIMESTAMP),
('6.5', 'US Women', CURRENT_TIMESTAMP),
('7', 'US Women', CURRENT_TIMESTAMP),
('7.5', 'US Women', CURRENT_TIMESTAMP),
('8', 'US Women', CURRENT_TIMESTAMP),
('8.5', 'US Women', CURRENT_TIMESTAMP),
('9', 'US Women', CURRENT_TIMESTAMP),
('9.5', 'US Women', CURRENT_TIMESTAMP),
('10', 'US Women', CURRENT_TIMESTAMP),
('10.5', 'US Women', CURRENT_TIMESTAMP),
('11', 'US Women', CURRENT_TIMESTAMP),
('11.5', 'US Women', CURRENT_TIMESTAMP),
('12', 'US Women', CURRENT_TIMESTAMP)
ON CONFLICT (value, unit) DO UPDATE
SET tanggal_update = CURRENT_TIMESTAMP;

-- Insert UK sizes
INSERT INTO master_sizes (value, unit, tanggal_update) VALUES
('2', 'UK', CURRENT_TIMESTAMP),
('2.5', 'UK', CURRENT_TIMESTAMP),
('3', 'UK', CURRENT_TIMESTAMP),
('3.5', 'UK', CURRENT_TIMESTAMP),
('4', 'UK', CURRENT_TIMESTAMP),
('4.5', 'UK', CURRENT_TIMESTAMP),
('5', 'UK', CURRENT_TIMESTAMP),
('5.5', 'UK', CURRENT_TIMESTAMP),
('6', 'UK', CURRENT_TIMESTAMP),
('6.5', 'UK', CURRENT_TIMESTAMP),
('7', 'UK', CURRENT_TIMESTAMP),
('7.5', 'UK', CURRENT_TIMESTAMP),
('8', 'UK', CURRENT_TIMESTAMP),
('8.5', 'UK', CURRENT_TIMESTAMP),
('9', 'UK', CURRENT_TIMESTAMP),
('9.5', 'UK', CURRENT_TIMESTAMP),
('10', 'UK', CURRENT_TIMESTAMP),
('10.5', 'UK', CURRENT_TIMESTAMP),
('11', 'UK', CURRENT_TIMESTAMP),
('11.5', 'UK', CURRENT_TIMESTAMP),
('12', 'UK', CURRENT_TIMESTAMP),
('12.5', 'UK', CURRENT_TIMESTAMP),
('13', 'UK', CURRENT_TIMESTAMP)
ON CONFLICT (value, unit) DO UPDATE
SET tanggal_update = CURRENT_TIMESTAMP; 